# Path related
dataset_path: data/raw/rawdataset
dataset_cleaned_path: data/processed/clean_dataset.pkl
train_set_path:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
valid_set_path:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
test_set_path:
- data/processed/x_test.pkl
- data/processed/y_test.pkl
production_model_path: /home/riyan/MLProject/pencemaran_udara_jakarta/models/production_model.pkl

training_log_path: log/training_log.json

# Debug related
print_debug: true

# Columns by data type related
int_columns:
- stasiun
- pm10
- pm25
- so2
- co
- o3
- no2
- max
- critical
- categori

# Predictors and label related
label: categori
predictors:
- stasiun
- pm10
- pm25
- so2
- co
- o3
- no2
- max
- critical

# Range of data related
range_stasiun:
- 0
- 4
range_pm10:
- 15
- 179
range_pm25:
- 20
- 174
range_so2:
- 4
- 82
range_co:
- 2
- 30
range_o3:
- 8
- 81
range_no2:
- 4
- 65
range_max:
- 26
- 179
range_critical:
- 0
- 3
range_categori:
- 0
- 1

# Splitting related
test_size: 0.1
valid_size: 0.3